# Generated by Django 5.0.4 on 2024-05-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_mymodel_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='personal_project',
        ),
    ]
